spring.data.mongodb.uri=${MONGODB_URI}
server.port=${PORT:8080}
app.base-url=${APP_BASE_URL:http://localhost:8080}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always